from __future__ import annotations

import json
from pathlib import Path

from etl_validation_tool.comparator import build_sql_preview
from etl_validation_tool.config import TablePair


def generate_testcase_manifest(table_pairs: list[TablePair], output_path: Path) -> Path:
    payload = []
    for idx, pair in enumerate(table_pairs, start=1):
        payload.append(
            {
                "test_id": f"AUTO_TC_{idx:04d}",
                "name": f"Validate {pair.source_fqn} vs {pair.target_fqn}",
                "table_pair": {
                    "source_connection": pair.source_connection,
                    "source_schema": pair.source_schema,
                    "source_table": pair.source_table,
                    "target_connection": pair.target_connection,
                    "target_schema": pair.target_schema,
                    "target_table": pair.target_table,
                },
                "join_keys": pair.join_keys,
                "query_preview": build_sql_preview(pair, pair.compare_columns or []),
                "priority": "High",
                "tags": ["etl", "reconciliation", "autogenerated"],
            }
        )

    output_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return output_path


def generate_pytest_module(manifest_path: Path, destination: Path) -> Path:
    module_text = f'''import json
from pathlib import Path


def test_generated_cases_have_join_keys():
    manifest = json.loads(Path(r"{manifest_path}").read_text(encoding="utf-8"))
    assert manifest, "No testcases were generated"
    for case in manifest:
        assert case["join_keys"], f"Join keys missing for {{case['test_id']}}"
'''
    destination.write_text(module_text, encoding="utf-8")
    return destination
