from __future__ import annotations

import json
from pathlib import Path

import streamlit as st

from etl_validation_tool.config import TablePair
from etl_validation_tool.management_store import TestManagementStore
from etl_validation_tool.tableau_kpi_validator import KPIExpectation, TableauKPIValidator
from etl_validation_tool.testcase_generator import generate_testcase_manifest

st.set_page_config(page_title="ETL Validation Workbench", layout="wide")

st.title("ETL Testing Automation Workbench")
st.caption("Structured ETL reconciliation + unstructured checks + Tableau KPI validation.")

uploaded = st.file_uploader(
    "Upload table mapping JSON", type=["json"], help="JSON list with source/target schema, table, keys, and connection names"
)

if uploaded:
    mappings = json.loads(uploaded.read().decode("utf-8"))
    table_pairs = [TablePair(**row) for row in mappings]

    st.subheader("Select tables for validation")
    select_all = st.checkbox("Select all tables", value=True)

    selected = []
    for pair in table_pairs:
        label = f"{pair.source_connection}:{pair.source_fqn} -> {pair.target_connection}:{pair.target_fqn}"
        if select_all or st.checkbox(label, value=False):
            selected.append(pair)

    if st.button("Generate Structured Testcases"):
        out = Path("artifacts")
        out.mkdir(exist_ok=True)
        manifest = generate_testcase_manifest(selected, out / "generated_testcases.json")
        st.success(f"Generated {len(selected)} structured testcases: {manifest}")
        st.code(manifest.read_text(encoding="utf-8"), language="json")

    st.subheader("Test Management (local)")
    store = TestManagementStore(Path("artifacts/test_management.db"))
    if st.button("Register selected testcases"):
        for i, pair in enumerate(selected, start=1):
            store.register_test_case(
                external_id=f"AUTO_TC_{i:04d}",
                name=f"Validate {pair.source_fqn} vs {pair.target_fqn}",
                table_pair=f"{pair.source_connection}:{pair.source_fqn}->{pair.target_connection}:{pair.target_fqn}",
                query_preview="Auto generated by tool",
            )
        st.success(f"Registered {len(selected)} testcases into local management DB")

    if st.button("Show recent executions"):
        rows = store.latest_results()
        st.dataframe(rows, use_container_width=True)
else:
    st.info("Upload a mapping JSON file to begin.")

st.divider()
st.subheader("Tableau KPI post-validation")

tableau_csv = st.file_uploader("Upload Tableau CSV export", type=["csv"], key="tableau_csv")
expectation_json = st.file_uploader("Upload KPI expectations JSON", type=["json"], key="kpi_json")

if tableau_csv and expectation_json and st.button("Validate Tableau KPIs"):
    temp_dir = Path("artifacts")
    temp_dir.mkdir(exist_ok=True)
    csv_path = temp_dir / "tableau_export.csv"
    exp_path = temp_dir / "kpi_expectations.json"
    csv_path.write_bytes(tableau_csv.read())
    exp_path.write_bytes(expectation_json.read())

    expectations = [KPIExpectation(**row) for row in json.loads(exp_path.read_text(encoding="utf-8"))]
    results = TableauKPIValidator().validate_from_csv(csv_path, "kpi_name", "kpi_value", expectations)
    st.dataframe([r.__dict__ for r in results], use_container_width=True)
